lib/gush/cli.rb

CLI class build configuration hash basing on given options or default values. In this manner we can require Gushfile from configuration path instead of relying on options which might not be passed.

Update CLI gushfile method to use configuration

---

lib/gush/job.rb

As discussed in https://github.com/chaps-io/gush/issues/17.
I've added the code you've provided to the `Gush::Job` class - tested in on my working development, everything is logging smooth.

Add a Sidekiq logger to jobs

---

Gemfile
lib/gush/client.rb
lib/gush/job.rb
lib/gush/worker.rb
lib/gush/workflow.rb
spec/features/integration_spec.rb
spec/lib/gush/client_spec.rb
spec/lib/gush/workflow_spec.rb
spec/spec_helper.rb

Hey, like we've discussed in https://github.com/chaps-io/gush/issues/21, I need to have unique names for jobs that run the same class with different params. 
Here is my solution to the problem - I've also updated rspec tests for it (all green now), as well as added mine that is using the new `nameize_payloads!` method. What it does is changing the way payloads are delivered - they can be either delivered as an array of strings or hashes, depending on how detailed your payloads needs to be:
```ruby
#normal approach
payloads['DummyJob'] => ['one','two','three']
#hashes approach
payloads['DummyJob'] => [{:id => 'DummyJob-1',:payload => 'one'}]
```
Hope that you can merge this, so everyone can use it.

Assign unique names for jobs with the same class

---

lib/gush/workflow.rb
spec/gush/workflow_spec.rb

Method is used to restart all failed jobs within workflow.

Implements #continue method

---

Gemfile
gush.gemspec
lib/gush.rb
lib/gush/configuration.rb
lib/gush/json.rb
lib/gush/worker.rb
spec/spec_helper.rb

Gush is incompatible with JRuby, as yajl-ruby is a Ruby wrapper for the C yajl library. MultiJson is an interface which will call an underlying library to parse the JSON. 
This pull request keeps yajl-ruby for Ruby platforms, and MultiJson should use continue to use it if the user has not specified a different engine. 
Bundler will not fail on attempting to install the native C extensions.

Updated to MultiJson (JSON engine interface)

---

lib/gush/client.rb
lib/gush/job.rb
lib/gush/workflow.rb
spec/gush/workflow_spec.rb

This PR improves performance in 3 places:
- uses `SCAN` instead of `KEYS` to be non-blocking
- stops serializing jobs into workflow JSON (breaking change but unlikely anyone relied on this)
- `parents_succeeded?` is no longer eagerly checking all parents and instead does inverse to look for the first non-succeeded job

Performance improvements

---

README.md
lib/gush/cli.rb
lib/gush/client.rb
lib/gush/configuration.rb
lib/gush/workflow.rb
spec/gush/client_spec.rb

Per discussion in https://github.com/chaps-io/gush/issues/26 here is a first attempt at expiring workflow keys.  Please consider for including this feature in the library or modify as appropriate.  
1. Added config.ttl to use Redis TTL to expire keys set for various work…
2. Added expire_workflow and expire_job methods to client
3. Right now you need to manually call expire! to set expiration for the workflow keys.  Alternative design would be to leverage callback that will automatically call this after last job in workflow completes. 
I added a test for Client.expire_workflow but I think fakeredis TTL does not work quite the same as Redis (had issues w it in the past).  
On separate note I updated README with suggestion on how to check whether workflow is running w particular class name. …

Using Redis TTL to expire keys after a certain point

---

gush.gemspec

Hi, thank you for your work with Gush. We're considering using it for a Rails 4.2 project but the `gemspec` currently has a `~> 5.0` dependency. However, we don't think that there are any meaningful differences for `gush` — all tests pass with 4.2. 
Is there anything else that we should be checking? If not, what do you think about merging this? I imagine there are still a good number of Rails 4 projects out there. 
Thank you!

Downgrade ActiveJob dependency to 4.2

---

lib/gush/client.rb
lib/gush/job.rb
lib/gush/workflow.rb
spec/gush/job_spec.rb
spec/gush/workflow_spec.rb
spec/spec_helper.rb

As discussed on https://github.com/chaps-io/gush/issues/55

Store gush jobs on redis hash instead of plain keys

---

lib/gush/client.rb
lib/gush/job.rb
lib/gush/workflow.rb
spec/gush/job_spec.rb

#39 Added queue support as per the latest code.

Allow setting queue for each job

---

lib/gush/worker.rb
spec/gush/worker_spec.rb
spec/spec_helper.rb

This commit is trying to fix issue RedisMutex::LockError on
https://github.com/chaps-io/gush/issues/57.
Whenever we have the error, it simply enqueues another worker.
At the begin of the worker, if the job is succedeed, we simply call
`enqueue_outgoing_jobs` again.

Try to enqueue outgoing jobs in another worker

---

.gitignore
.travis.yml
gush.gemspec
lib/gush/client.rb
spec/gush/client_spec.rb

- Previously (before commit a94719b) each gush object that had a method `client` with a memoized `Client.new` would create a new redis connection. This was causing a lot of redis connections for us & causing us to hit the limit of our redis instance. With commit a94719b, we now hold only open redis connection per thread via a thread local class variable. This lowers the amount of redis connection substantially.
- Commit 1c12ce2 fixes a bug where TTL was not being set correct for job key causing job keys to never be expired.

Limit number of redis connections and fix ttl bug

---

gush.gemspec

We are using Gush with Rails/ActiveJob 6 in our application & we are not thus far seeing any issue.

Gush can work with ActiveJob 6, no need to limit it to < 6.0.

---

README.md
lib/gush/cli.rb
lib/gush/configuration.rb
lib/gush/worker.rb
spec/gush/configuration_spec.rb
spec/gush/worker_spec.rb
spec/spec_helper.rb

Currently, RedisMutex's `sleep` and `block` options are fixed with these 2 values 0.3 and 2, respectively. When the number of jobs is large, we will frequently get the error `RedisMutex::LockError`.
I have updated the code and opened this PR to make them customizable based on the number of jobs of a workflow. 
Additionally, it also helps to solve this issue https://github.com/chaps-io/gush/issues/57.

Allow RedisMutex’s locking duration and polling interval to be customizable

---

.github/workflows/ruby.yml
Gemfile

Add Rails version to CI matrix. The versions of rails in matrix, the supported major versions by gush currently.

Add Rails version to CI matrix

---

README.md
lib/gush/client.rb
lib/gush/job.rb
lib/gush/workflow.rb
spec/gush/client_spec.rb
spec/gush/workflow_spec.rb
spec/spec_helper.rb

This PR adds `wait` as a paremeter to `run` method on `Gush::Workflow`.

Add wait parameter to jobs

---

gush.gemspec
spec/gush/client_spec.rb

Updating gemspec to allow redis v5.
Fix a test that did not have an id, redis v5 will error on an attempt to set a nil key in a hash.

Update redis dependency  >= 3.2, < 6

---

.github/workflows/ruby.yml
gush.gemspec
lib/gush/version.rb
spec/features/integration_spec.rb
spec/spec_helper.rb

This PR introduces following changes:
- Drop support for EOL ruby versions: now at least ruby 3.0.0 is required
- Drop support for EOL rails versions: at least rails 6.1.0 is required
- small patch for integration tests

Update gush dependencies

---

lib/gush/job.rb
spec/gush/job_spec.rb

Just added missing :wait attribute to Gush::Job#as_json because that argument was skipped when Gush::Job#persist_job called so sidekiq job was performed with no delay even if :wait was specified

add missing json attribute to Gush::Job

---

README.md
lib/gush/client.rb
lib/gush/workflow.rb
spec/gush/client_spec.rb
spec/gush/workflow_spec.rb
spec/spec_helper.rb

For shared functionality across Workflow classes that depends on some variable
data, it's useful to have named parameters for the Workflow that are
automatically forwarded to all Job instances.
This commit adds a `globals` keyword arg to the Workflow initializer, which
should be a hash that is then stored in a `globals` hash attribute, is
persisted, and is merged into the `params` sent to each Job instance.
For workflows that take a larger number of parameters or optional parameters,
it's useful to specify these as keyword arguments rather than positional ones.
This commit adds support to `Workflow#initialize` for kwargs, and stores them
in a new `kwargs` attribute.

Add globals and kwargs to Workflow and Job

---

lib/gush/client.rb
lib/gush/workflow.rb
spec/features/integration_spec.rb
spec/gush/client_spec.rb
spec/gush/workflow_spec.rb

Previously, `Workflow#configure` was called every time a Workflow was instantiated. This could create broken dependency graphs, e.g. if a configure method sets up job dependencies based on some mutable data like a timestamp argument or a database value.
Instead, serialize workflow dependencies along with the rest of a workflow's data and reload it via `Client#workflow_from_hash` and tell `Workflow#initialize` not to run setup/configure.
Note that for backwards compatibility with workflows persisted before this change, the setup method will still be called if dependencies in the deserialized hash are nil.

Persist dependencies so that `Workflow#configure` is not required on load

---

lib/gush/client.rb
spec/gush/client_spec.rb

Previously, the wrong key prefix was used, which means that this method was not actually checking whether a workflow id was already in use.

Fixed the workflow redis key format used in `Client#next_free_workflow_id`

---

README.md
lib/gush/client.rb
lib/gush/job.rb
spec/gush/job_spec.rb

This delegation allows for Gush users to easily override the enqueing behavior to their custom job class, e.g. to support additional ActiveJob options or enqueing behaviors (e.g synchronous with `perform_now`).

`Gush::Client` now delegates the `ActiveJob.perform_later` call to `Gush::Job`

---

lib/gush/workflow.rb
spec/gush/workflow_spec.rb

Update default workflow status to pending when workflow is pending to start
This implements the same change as #89, with specs added.

Fix workflow status when the workflow is pending to start

---

.github/workflows/ruby.yml
.rubocop.yml
gush.gemspec
lib/gush/cli.rb
lib/gush/cli/overview.rb
lib/gush/client.rb
lib/gush/graph.rb
lib/gush/job.rb
lib/gush/version.rb
lib/gush/worker.rb
lib/gush/workflow.rb
spec/features/integration_spec.rb
spec/gush/workflow_spec.rb
spec/spec_helper.rb

This PR includes three commits (that can be squashed before merging):
1. Added rubocop (and related gems) and autogenerated a config file that matches enabled cops to the existing code style. Also added rubocop step to GitHub actions.
2. Manually disabled a few cops that depend on arbitrarily chosen lengths (e.g. `Metrics/MethodLength`).
3. Enabled some cops and fixed related warnings.
For the last commit, I chose cops that were very easy to update the code to adhere to and, in some cases, relate to preventing bugs. I mostly avoided cops that involve more personal code style preferences (e.g. spacing, alignment, naming). If those changes don't follow this project's preferred styling, I'm happy to roll some or all of them back.

Added rubocop for code style consistency

---

README.md
lib/gush.rb
lib/gush/cli.rb
lib/gush/client.rb
lib/gush/migrate/1_create_gush_workflows_created.rb
lib/gush/migration.rb
lib/gush/workflow.rb
spec/gush/client_spec.rb
spec/gush/migrate/1_create_gush_workflows_created_spec.rb
spec/gush/migration_spec.rb
spec/gush/workflow_spec.rb

This commit makes several interrelated changes:
1. Replaced the redis key scan to find job keys in `Client#find_workflow` with job class name persistence in `Workflow#to_hash`. This significantly improves performance when loading many workflows because it avoids n key scans.
2. Added `Client#workflow_ids` with sorting by creation timestamp and pagination as an alternative to `Client#all_workflows`, which has performance issues in large keyspaces and returns unwieldy amounts of data given a large number of workflows.
3. Added workflow and job indexes by `created_at` and `expires_at` timestamps. The former is necessary for paging through sorted workflow ids, and the latter is necessary to remove data on expiration.
4. Replace use of redis key TTL with explicit expiration via …

Improved redis performance in large keyspace, added pagination, and auto-expiration
